'use client'
import { SocketContextProvider } from '@/context/socketContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { invoke } from '@tauri-apps/api'

import Greet from './greet'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en">
      <SocketContextProvider>
        <Greet />
        <body className={inter.className}>{children}</body>
      </SocketContextProvider>
    </html>
  );
}
